// ПРАВИЛА (RULES-gologin.md): 1) НИКОГДА не убивать профиль через pkill/kill -9 — GoLogin не синхронизирует
// профиль и акк ВЫЛОГИНИВАЕТСЯ; закрывать только через gl.stopLocal()/DELETE /web. 2) Один профиль — одна
// сессия. 3) Профиль залогиненного вручную акка не трогать. 4) Любая браузерная операция не висит >60с:
// таймаут → релоад и повтор (макс 2), затем следующая цель. 5) Успех публикации = композер очистился.
// Сторож GoLogin: пингует cloud-коннект, при восстановлении тихо шлёт в ТГ и толкает бэклог ответить на волну.
const fs=require('fs');const {Client}=require('pg');const {chromium}=require('playwright-core');const {execSync}=require('child_process');
const DBURL=fs.readFileSync('/tmp/dburl.txt','utf8').trim();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function tg(t){try{const b=fs.readFileSync('/tmp/tg_bot.txt','utf8').trim(),ch=fs.readFileSync('/tmp/tg_chat.txt','utf8').trim();fetch(`https://api.telegram.org/bot${b}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:ch,text:t,disable_notification:true})}).catch(()=>{});}catch{}}
async function tryConn(){const c=new Client({connectionString:DBURL,ssl:{rejectUnauthorized:false},connectionTimeoutMillis:15000});await c.connect();const a=(await c.query("SELECT a.gologin_profile_id AS pid, g.gologin_token AS tok FROM accounts a JOIN account_groups g ON g.id=a.group_id WHERE coalesce(g.backlog,false)=true AND a.deleted_at IS NULL LIMIT 1")).rows[0];await c.end();await fetch('https://api.gologin.com/browser/'+a.pid+'/web',{method:'DELETE',headers:{Authorization:'Bearer '+a.tok}}).catch(()=>{});await sleep(5000);const u=new URL('wss://cloudbrowser.gologin.com/connect');u.searchParams.set('token',a.tok);u.searchParams.set('profile',a.pid);try{const b=await chromium.connectOverCDP(u.toString(),{timeout:35000});await b.close().catch(()=>{});await fetch('https://api.gologin.com/browser/'+a.pid+'/web',{method:'DELETE',headers:{Authorization:'Bearer '+a.tok}}).catch(()=>{});return true;}catch{return false;}}
(async()=>{let downSince=Date.now();for(;;){const ok=await tryConn();if(ok){const min=Math.round((Date.now()-downSince)/60000);console.log('[gl-watch] GoLogin ОЖИЛ (лежал ~'+min+'мин) — толкаю бэклог');tg('🟢 GoLogin восстановился (лежал ~'+min+'мин). Движки догоняют волну «Промт» на посту Алины.');try{execSync('kill $(cat /tmp/backlog.pid) 2>/dev/null; sleep 2; cd /Users/qq/Desktop/neironka-poster && nohup node backlog_safe.cjs > /tmp/backlog.log 2>&1 & echo $! > /tmp/backlog.pid',{shell:'/bin/zsh'});}catch{}return;}console.log('[gl-watch] GoLogin ещё лежит');await sleep(180000);}})().catch(e=>console.error(e.message));
